name: environment_OCG_Saildrone
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cartopy
  - dask
  - jupytext
  - jupyterlab>=3
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - python
  - seawater
  - xarray
  - pip:
    - PyCO2SYS
